In [18]:
#Consider the below code to answer further questions:


import numpy as np

list_ = [ '1' , '2' ,' 3' ,' 4' , '5' ]

array_list = np.array(object = list_)


In [19]:
array_list

array(['1', '2', ' 3', ' 4', '5'], dtype='<U2')

In [20]:
# yes, there is difference between list_ and array_list. "list_" is a list type where array_list is a numpy.ndarray

In [21]:
array_list.dtype

dtype('<U2')

In [22]:
type(list_)

list

In [23]:
def data_type(x,y):
    for i in x:
        print("this is list data type:",type(i))
    for j in y:
        print("this is array_list data type:",type(j))

In [24]:
data_type(list_,array_list)

this is list data type: <class 'str'>
this is list data type: <class 'str'>
this is list data type: <class 'str'>
this is list data type: <class 'str'>
this is list data type: <class 'str'>
this is array_list data type: <class 'numpy.str_'>
this is array_list data type: <class 'numpy.str_'>
this is array_list data type: <class 'numpy.str_'>
this is array_list data type: <class 'numpy.str_'>
this is array_list data type: <class 'numpy.str_'>


In [25]:
array_list = np.array(object = list_, dtype = int)

In [26]:
array_list

array([1, 2, 3, 4, 5])

In [28]:
data_type(list_,array_list)# yes their is the diffrence because we have changed the data type of array_list 

this is list data type: <class 'str'>
this is list data type: <class 'str'>
this is list data type: <class 'str'>
this is list data type: <class 'str'>
this is list data type: <class 'str'>
this is array_list data type: <class 'numpy.int64'>
this is array_list data type: <class 'numpy.int64'>
this is array_list data type: <class 'numpy.int64'>
this is array_list data type: <class 'numpy.int64'>
this is array_list data type: <class 'numpy.int64'>


In [29]:
#Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

In [31]:
# shape num_array
print(num_array.shape)

(2, 3)


In [32]:
# size num_array
print(num_array.size)

6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [62]:
import numpy.matlib as nm
arr=nm.zeros((3,3))

In [63]:
arr

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [64]:
arr1=nm.eye(5)

In [65]:
arr1

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [44]:
identity_matrix = np.identity(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
